### ISSUE TITLE
'Unmaintained. Please do not use anymore.'

### ISSUE THREAD

**Issue by Sigurs** [mkotb/MineCloud#42]
Self explanatory. Huge issue as this is a big part of certain fringe subcultures.

**Comment by ajvpot** [comment]
You're free to fork it.

**Comment by Sigurs** [comment]
@ajvpot 
![giphy](https://cloud.githubusercontent.com/assets/10909187/24318082/712aa5c6-1108-11e7-979e-1750c0e9bd74.gif)

**Comment by Aipaloovik** [comment]
Don't tell me how to live my life. I'll use whatever fringe code I want to!

**Comment by mkotb** [comment]
lol... On a serious note, I can't maintain it anymore and the biggest issue is documentation for getting the setup to work just right to avoid running MineCloud successfully (especially since software (dependencies) have updated and the codebase has not kept up with that due to inactivity). If anyone is interested in maintaining it, I'd be happy to open a discussion about how to work around it, or they can create a fork :P
